### PR TITLE
Disable File Open menu item

### LINKED ISSUE #132: Menu File -> Open File... should be disabled until it works
Clicking on File -> Open File throws an exception because of strict access control. Need to work an access control UI, but until then the menu button can be simply disabled / hidden.

### PR DESCRIPTION
**Pull request by chetankothari**
This prevents the `java.security.AccessControlException: access denied`
exception.

Closes #132

### CODE REVIEW

File: src/Primary_Extension/org/lobobrowser/primary/ext/ComponentSource.java [hunk 1]
```diff
@@ -179,7 +179,10 @@ public JMenu getFileMenu() {
     openMenu.add(menuItem("New Window", 'N', KeyStroke.getKeyStroke(KeyEvent.VK_N, CMD_CTRL_KEY_MASK),
         this.actionPool.blankWindowAction));
     openMenu.add(menuItem("Cloned Window", 'C', this.actionPool.clonedWindowAction));
-    openMenu.add(menuItem("File...", 'F', KeyStroke.getKeyStroke(KeyEvent.VK_O, CMD_CTRL_KEY_MASK), this.actionPool.openFileAction));
+    final JMenuItem fileMenuItem = menuItem("File...", 'F', KeyStroke.getKeyStroke(KeyEvent.VK_O, CMD_CTRL_KEY_MASK), this.actionPool.openFileAction);
+    // TODO enable the menu item once access control UI is implemented
+    fileMenuItem.setEnabled(false);
```
Comment (chetankothari) [inline src/Primary_Extension/org/lobobrowser/primary/ext/ComponentSource.java]: Was thinking if we should pass in a flag to `menuItem` to return a disabled item, or use disabled action.

Comment (hrj) [inline src/Primary_Extension/org/lobobrowser/primary/ext/ComponentSource.java]: A flag to `menuItem` would be more "functional", yeah. But if it is used only in this one case, I would leave it aside as a minor thing.

**Comment by hrj** [comment]
Merged; thanks!

File: src/Primary_Extension/org/lobobrowser/primary/ext/ComponentSource.java (hunk 1 above)
Comment (chetankothari) [inline src/Primary_Extension/org/lobobrowser/primary/ext/ComponentSource.java]: Makes sense. Will check for usage and see if we can get that done.
